# -*- coding: utf-8 -*-
"""BettingEdge_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5ZrcH_PLO7TRQmTYMxAEzu8HJyfMTqc
"""

import joblib
from dataclasses import dataclass, field
from typing import Tuple, Dict, Any

import os
import sys
import pandas as pd
import numpy as np
import joblib
import nflreadpy as nfl
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────
TARGET_SEASON   = 2025
EDGE_THRESHOLD  = 1.0
TRACKER_PATH    = 'predictions_tracker.csv'
ALLPRO_CSV_PATH = 'nfl_allpro_1997_2025.csv'
MODEL_PATH      = 'fantasy_model.pkl'

# Mode is passed as a command line argument
# python predict.py monday
# python predict.py thursday
# python predict.py sunday
MODE = sys.argv[1] if len(sys.argv) > 1 else 'thursday'
print(f"Running in {MODE.upper()} mode — {datetime.now().strftime('%Y-%m-%d %H:%M')}")

def get_week_info(season):
    raw = nfl.load_schedules([season])
    schedule = raw.to_pandas() if hasattr(raw, 'to_pandas') else pd.DataFrame(raw)

    today = pd.Timestamp.now().normalize()

    reg = schedule[
        (schedule['season'] == season) &
        (schedule['game_type'] == 'REG')
    ].copy()

    # Future games = no result yet
    future = reg[reg['result'].isna()]
    # Completed games = result exists
    completed = reg[reg['result'].notna()]

    if future.empty:
        # Season over
        return None, int(completed['week'].max())

    upcoming_week  = int(future['week'].min())
    previous_week  = upcoming_week - 1 if upcoming_week > 1 else None

    return upcoming_week, previous_week

TARGET_WEEK, PREV_WEEK = get_week_info(TARGET_SEASON)
print(f"Upcoming week: {TARGET_WEEK} | Previous week: {PREV_WEEK}")

def update_results(season, week):
    if not os.path.exists(TRACKER_PATH):
        print("No tracker found — skipping results update")
        return

    print(f"Updating results for season {season} week {week}...")

    tracker = pd.read_csv(TRACKER_PATH)

    raw = nfl.load_schedules([season])
    sched = raw.to_pandas() if hasattr(raw, 'to_pandas') else pd.DataFrame(raw)

    actual = sched[
        (sched['season'] == season) &
        (sched['week']   == week)
    ][['game_id', 'result']].rename(columns={'result': 'actual_margin'})

    if actual['actual_margin'].isna().all():
        print(f"Results not yet available for week {week} — skipping")
        return

    mask    = (tracker['season'] == season) & (tracker['week'] == week)
    indices = tracker[mask].index

    if len(indices) == 0:
        print(f"No predictions found for week {week} — skipping")
        return

    rows = tracker.loc[indices].copy()
    rows = rows.merge(actual, on='game_id', how='left', suffixes=('_old', '_new'))
    rows['actual_margin'] = rows['actual_margin_new']
    rows = rows.drop(columns=['actual_margin_old', 'actual_margin_new'], errors='ignore')
    rows['home_covered']  = (rows['actual_margin'] > rows['spread_line']).astype(int)
    rows['model_correct'] = ((rows['model_edge'] > 0) == (rows['home_covered'] == 1)).astype(int)

    tracker.loc[indices, 'actual_margin'] = rows['actual_margin'].values
    tracker.loc[indices, 'home_covered']  = rows['home_covered'].values
    tracker.loc[indices, 'model_correct'] = rows['model_correct'].values
    tracker.to_csv(TRACKER_PATH, index=False)

    correct = int(rows['model_correct'].sum())
    total   = len(rows)
    print(f"✅ Week {week} results updated — ATS: {correct}/{total} ({correct/total*100:.1f}%)")

def log_predictions(results_df, season, week, mode):
    log = results_df[['game_id', 'home_team', 'away_team', 'gameday',
                       'spread_line', 'predicted_margin',
                       'model_edge', 'recommendation']].copy()
    log['season']        = season
    log['week']          = week
    log['mode']          = mode          # tracks which run produced this
    log['logged_at']     = datetime.now().strftime('%Y-%m-%d %H:%M')
    log['actual_margin'] = None
    log['home_covered']  = None
    log['model_correct'] = None

    if os.path.exists(TRACKER_PATH):
        tracker = pd.read_csv(TRACKER_PATH)

        # Check if this week already has predictions
        existing_mask = (
            (tracker['season'] == season) &
            (tracker['week']   == week)
        )

        if existing_mask.any():
            # UPDATE existing predictions — spreads and edges may have shifted
            print(f"Updating existing week {week} predictions ({mode} refresh)...")
            tracker = tracker[~existing_mask]   # drop old rows for this week

        updated = pd.concat([tracker, log], ignore_index=True)
        updated.to_csv(TRACKER_PATH, index=False)
        print(f"✅ Week {week} predictions saved ({mode} run — {len(log)} games)")

    else:
        log.to_csv(TRACKER_PATH, index=False)
        print(f"✅ Tracker created with week {week} predictions ({len(log)} games)")

"""## load model"""

@dataclass(frozen=True)
class FinalCfg:
    test_size: float = 0.2
    random_state: int = 42
    oof_splits: int = 5
    weight_win: float = 2.0
    weight_loss: float = 1.0
    drop_non_features: Tuple[str, ...] = ('game_id','home_team','away_team','season','week')
    categorical_cols: Tuple[str, ...] = ('roof','surface')
    boolean_cols: Tuple[str, ...] = (
        'is_playoff','is_final_week','home_qb_switch','away_qb_switch','is_home_qb_new','is_away_qb_new'
    )
    # For OOF weighting model
    base_xgb_params: Dict[str, Any] = field(default_factory=lambda: dict(
        n_estimators=500, max_depth=3, learning_rate=0.01, min_child_weight=3,
        subsample=0.6, colsample_bytree=0.6, reg_alpha=1.0, reg_lambda=3.0,
        objective='reg:squarederror', random_state=42, tree_method='hist', n_jobs=1
    ))

res = joblib.load('/content/drive/MyDrive/BettingEdgeContinued/fantasy_model.pkl')

print(res.keys())
# → dict_keys(['mae', 'r2', 'y_test', 'y_pred', 'pipeline', 'used_columns', 'config'])

# The pipeline is what actually makes predictions
pipeline = res["pipeline"]
pipeline

# This tells you EXACTLY what columns the model was trained on
pre = pipeline.named_steps["preprocessor"]
pre

cat_cols  = pre.transformers_[0][2]   # OrdinalEncoder columns (roof, surface)
num_cols  = pre.transformers_[1][2]   # passthrough columns (everything else)

print("Categorical features:", cat_cols)
print("Numeric/Boolean features:", num_cols)
print("\nTotal features expected:", len(cat_cols) + len(num_cols))

pip install nflreadpy

import nflreadpy as nfl
import pandas as pd

raw = nfl.load_schedules([2025])

print(type(raw))   # confirms it's a polars DataFrame

# Convert Polars → Pandas correctly
schedule = raw.to_pandas()

print(schedule.shape)
print(schedule.columns.tolist())

"""## simple feature wrangling"""

key_cols = [
    'game_id', 'home_team', 'away_team', 'week', 'season',
    'spread_line', 'total_line', 'away_rest', 'home_rest',
    'div_game', 'roof', 'surface', 'temp', 'wind', 'result'
]

for col in key_cols:
    status = "✅" if col in schedule.columns else "❌ MISSING"
    print(f"{status}  {col}")

print("\n\nAll available columns:")
print(schedule.columns.tolist())

TARGET_WEEK = 10  # change this each week you want to predict

week_games = schedule[schedule['week'] == TARGET_WEEK]

# Show just the columns relevant to us
cols = ['game_id', 'home_team', 'away_team', 'gameday', 'gametime',
        'spread_line', 'total_line', 'away_rest', 'home_rest',
        'div_game', 'roof', 'surface', 'temp', 'wind']

print(week_games[cols].to_string())

# All completed games BEFORE the target week — used to build rolling features
history = schedule[
    (schedule['week'] < TARGET_WEEK) &
    (schedule['result'].notna())   # result is NaN for games not yet played
].copy()

# The games you actually want to predict
upcoming = schedule[schedule['week'] == TARGET_WEEK].copy()

# Dome games have no temp/wind — fill with season medians from history
upcoming['temp'] = upcoming['temp'].fillna(72)
upcoming['wind'] = upcoming['wind'].fillna(0)

print(f"History: {len(history)} completed games (weeks 1 through {TARGET_WEEK - 1})")
print(f"Upcoming: {len(upcoming)} games to predict in week {TARGET_WEEK}")

# These are the Group 1 features the model expects
group1_features = [
    'spread_line', 'away_rest', 'home_rest', 'total_line',
    'div_game', 'temp', 'wind', 'roof', 'surface'
]

print("Group 1 feature check for upcoming games:\n")
print(upcoming[group1_features].to_string())
print("\nNull counts:")
print(upcoming[group1_features].isnull().sum())

"""## pbp feature wrangling"""

raw_pbp = nfl.load_pbp([2025])
pbp = raw_pbp.to_pandas()

print(pbp.shape)
print(pbp['play_type'].value_counts())

pbp_rp = pbp[
    pbp['play_type'].isin(['run', 'pass']) &
    pbp['posteam'].notna() &
    pbp['defteam'].notna()
].copy()

print(pbp_rp.shape)
print(pbp_rp[['game_id', 'posteam', 'defteam', 'epa', 'yards_gained', 'play_type']].head(10))

# Offense stats — grouped by game and the team with the ball
off_stats = (
    pbp_rp
    .groupby(['game_id', 'posteam'])
    .agg(
        avg_epa=('epa', 'mean'),
        avg_yards=('yards_gained', 'mean'),
        play_count=('play_id', 'count')
    )
    .reset_index()
    .rename(columns={'posteam': 'team'})
)

# Defense stats — grouped by game and the team defending
def_stats = (
    pbp_rp
    .groupby(['game_id', 'defteam'])
    .agg(
        allowed_avg_epa=('epa', 'mean'),
        allowed_avg_yards=('yards_gained', 'mean'),
        allowed_play_count=('play_id', 'count')
    )
    .reset_index()
    .rename(columns={'defteam': 'team'})
)

print("Offense stats shape:", off_stats.shape)
print(off_stats.head())

# Pull just the week/season info from the schedule to attach to pbp stats
week_lookup = schedule[['game_id', 'week', 'season']].drop_duplicates()

off_stats = off_stats.merge(week_lookup, on='game_id', how='left')
def_stats = def_stats.merge(week_lookup, on='game_id', how='left')

print(off_stats[['game_id', 'team', 'week', 'avg_epa']].head(10))

# Sort by team and week so the rolling window goes in the right direction
off_stats = off_stats.sort_values(['team', 'season', 'week']).reset_index(drop=True)
def_stats = def_stats.sort_values(['team', 'season', 'week']).reset_index(drop=True)

# Rolling offense — shift(1) means "not including the current game"
# This is critical — you can't use a game's own stats to predict that game
for feat in ['avg_epa', 'avg_yards', 'play_count']:
    off_stats[f'rolling_{feat}'] = (
        off_stats
        .groupby('team')[feat]
        .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
    )

# Rolling defense
for feat in ['allowed_avg_epa', 'allowed_avg_yards', 'allowed_play_count']:
    def_stats[f'rolling_{feat}'] = (
        def_stats
        .groupby('team')[feat]
        .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
    )

print("Offense rolling stats:")
print(off_stats[['team', 'week', 'avg_epa', 'rolling_avg_epa']].head(15))

# We only need the rolling columns, not the raw game-level stats
off_rolling = off_stats[['game_id', 'team', 'rolling_avg_epa', 'rolling_avg_yards', 'rolling_play_count']]
def_rolling = def_stats[['game_id', 'team', 'rolling_allowed_avg_epa', 'rolling_allowed_avg_yards', 'rolling_allowed_play_count']]

# Merge home team offense
upcoming = upcoming.merge(
    off_rolling.rename(columns={'team': 'home_team', **{c: f'home_{c}' for c in off_rolling.columns if c.startswith('rolling')}}),
    on=['game_id', 'home_team'], how='left'
)

# Merge away team offense
upcoming = upcoming.merge(
    off_rolling.rename(columns={'team': 'away_team', **{c: f'away_{c}' for c in off_rolling.columns if c.startswith('rolling')}}),
    on=['game_id', 'away_team'], how='left'
)

# Merge home team defense
upcoming = upcoming.merge(
    def_rolling.rename(columns={'team': 'home_team', **{c: f'home_{c}' for c in def_rolling.columns if c.startswith('rolling')}}),
    on=['game_id', 'home_team'], how='left'
)

# Merge away team defense
upcoming = upcoming.merge(
    def_rolling.rename(columns={'team': 'away_team', **{c: f'away_{c}' for c in def_rolling.columns if c.startswith('rolling')}}),
    on=['game_id', 'away_team'], how='left'
)

print(upcoming[['home_team', 'away_team', 'home_rolling_avg_epa', 'away_rolling_avg_epa',
                 'home_rolling_allowed_avg_epa', 'away_rolling_allowed_avg_epa']].to_string())

# These were computed in your notebook as combinations of offense vs opponent defense
upcoming['epa_home_off_away_def_rolling_diff'] = (
    upcoming['home_rolling_avg_epa'] - upcoming['away_rolling_allowed_avg_epa']
)
upcoming['epa_home_def_away_off_rolling_diff'] = (
    upcoming['home_rolling_allowed_avg_epa'] - upcoming['away_rolling_avg_epa']
)
upcoming['avg_yards_home_off_away_def_rolling_diff'] = (
    upcoming['home_rolling_avg_yards'] - upcoming['away_rolling_allowed_avg_yards']
)
upcoming['avg_yards_home_def_away_off_rolling_diff'] = (
    upcoming['home_rolling_allowed_avg_yards'] - upcoming['away_rolling_avg_yards']
)
upcoming['play_count_home_off_away_def_rolling_diff'] = (
    upcoming['home_rolling_play_count'] - upcoming['away_rolling_allowed_play_count']
)
upcoming['play_count_home_def_away_off_rolling_diff'] = (
    upcoming['home_rolling_allowed_play_count'] - upcoming['away_rolling_play_count']
)

# Sanity check
diff_cols = [c for c in upcoming.columns if 'diff' in c]
print(upcoming[['home_team', 'away_team'] + diff_cols].to_string())

# How many of the 79 features do I have so far?
model_features = cat_cols + num_cols   # from step 1 earlier

have = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

"""## Historic Feature Wrangling"""

# Split each game into two rows — one for home team, one for away team
home_games = history[['season', 'week', 'home_team', 'away_team', 'home_score', 'away_score']].copy()
home_games.columns = ['season', 'week', 'team', 'opponent', 'team_score', 'opp_score']

away_games = history[['season', 'week', 'away_team', 'home_team', 'away_score', 'home_score']].copy()
away_games.columns = ['season', 'week', 'team', 'opponent', 'team_score', 'opp_score']

long_df = pd.concat([home_games, away_games], ignore_index=True)
long_df = long_df.sort_values(['team', 'season', 'week']).reset_index(drop=True)

# Mark wins
long_df['team_win'] = (long_df['team_score'] > long_df['opp_score']).astype(int)

print(long_df.head(10))
print(long_df.shape)

# shift() again — same reason as rolling PBP stats
# A team's win % entering a game can't include that game itself
long_df['win_pct'] = (
    long_df
    .groupby('team')['team_win']
    .transform(lambda x: x.shift(1).expanding().mean())
)

print(long_df[['team', 'week', 'team_win', 'win_pct']].head(20))

# Build a lookup: for each team/week, what is their win %?
win_pct_lookup = long_df[['season', 'week', 'team', 'win_pct']].copy()
win_pct_lookup.columns = ['season', 'week', 'opponent', 'opponent_win_pct']

# Merge opponent's win % onto each row
long_df = long_df.merge(win_pct_lookup, on=['season', 'week', 'opponent'], how='left')

print(long_df[['team', 'week', 'opponent', 'win_pct', 'opponent_win_pct']].head(20))

# Recent SOS = avg win % of last 3 opponents
long_df['recent_sos'] = (
    long_df
    .groupby('team')['opponent_win_pct']
    .transform(lambda x: x.shift(1).rolling(3, min_periods=1).mean().fillna(0))
)

# Season SOS = avg win % of all opponents so far this season
long_df['season_sos'] = (
    long_df
    .groupby('team')['opponent_win_pct']
    .transform(lambda x: x.shift(1).expanding().mean().fillna(0))
)

print(long_df[['team', 'week', 'recent_sos', 'season_sos']].head(20))

sos_lookup = long_df[['season', 'week', 'team', 'recent_sos', 'season_sos']].copy()

# We need the SOS for the TARGET week — meaning what was each team's SOS entering that week
# Since long_df only has history, we need the last known value per team
latest_sos = (
    sos_lookup
    .sort_values(['team', 'season', 'week'])
    .groupby('team')
    .last()
    .reset_index()
    [['team', 'recent_sos', 'season_sos']]
)

# Merge for home team
upcoming = upcoming.merge(
    latest_sos.rename(columns={
        'team': 'home_team',
        'recent_sos': 'home_recent_sos_opponent_avg',
        'season_sos': 'home_season_sos_opponent_avg'
    }),
    on='home_team', how='left'
)

# Merge for away team
upcoming = upcoming.merge(
    latest_sos.rename(columns={
        'team': 'away_team',
        'recent_sos': 'away_recent_sos_opponent_avg',
        'season_sos': 'away_season_sos_opponent_avg'
    }),
    on='away_team', how='left'
)

# Fill any NaN with 0 (same as notebook)
for col in ['home_recent_sos_opponent_avg', 'home_season_sos_opponent_avg',
            'away_recent_sos_opponent_avg', 'away_season_sos_opponent_avg']:
    upcoming[col] = upcoming[col].fillna(0)

print(upcoming[['home_team', 'away_team',
                'home_recent_sos_opponent_avg', 'away_recent_sos_opponent_avg',
                'home_season_sos_opponent_avg', 'away_season_sos_opponent_avg']].to_string())

upcoming['sos_diff'] = (
    upcoming['home_recent_sos_opponent_avg'] - upcoming['away_recent_sos_opponent_avg']
)
upcoming['season_sos_diff'] = (
    upcoming['home_season_sos_opponent_avg'] - upcoming['away_season_sos_opponent_avg']
)

print(upcoming[['home_team', 'away_team', 'sos_diff', 'season_sos_diff']].to_string())

have = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

"""## All pro features wrangling"""

allpro_df = pd.read_csv('/content/drive/MyDrive/BettingEdgeContinued/nfl_allpro_1997_2025.csv')  # update path to wherever your CSV lives
allpro_df = allpro_df[allpro_df['Team'] != '2TM'].copy()
print(allpro_df.shape)


# Confirm they're gone
print(f"\nTotal rows after dropping 2TM: {len(allpro_df)}")

print(allpro_df.columns.tolist())
print(allpro_df.head(10))
print(allpro_df['Year'].value_counts().sort_index())

team_map = {
    'STL': 'LA',    # Rams in St. Louis → now LA (not LAR, schedule uses LA)
    'LAR': 'LA',    # some years PFR uses LAR → schedule uses LA
    'OAK': 'LV',    # Raiders Oakland
    'LVR': 'LV',    # Raiders Las Vegas — PFR uses LVR, schedule uses LV
    'SD':  'LAC',   # Chargers San Diego
    'SDG': 'LAC',   # PFR alternate abbreviation for San Diego
    'NWE': 'NE',
    'KAN': 'KC',
    'GNB': 'GB',
    'NOR': 'NO',
    'TAM': 'TB',
    'SFO': 'SF',
}

allpro_df['Team'] = allpro_df['Team'].replace(team_map)

# Re-run the check — both sets should now be empty
allpro_teams   = set(allpro_df['Team'].unique())
schedule_teams = set(schedule['home_team'].unique())

print("Still mismatched:", allpro_teams - schedule_teams)

# For each season, look back 3 years and weight by recency
# Year - 1 = weight 4, Year - 2 = weight 2, Year - 3 = weight 1
# This rewards teams with recent all-pros more than older ones

all_games = []

for year in range(2006, 2026):   # 2026 = predict for 2025 season
    curr = []
    for yrs_back, weight in zip([1, 2, 3], [4, 2, 1]):
        prev_year = year - yrs_back
        df_prev = allpro_df[allpro_df['Year'] == prev_year].copy()
        df_prev['Weight'] = weight
        df_prev['Year_target'] = year
        curr.append(df_prev)

    combined = pd.concat(curr)

    # If a player was all-pro in multiple of the last 3 years,
    # only count them once (at their highest weight)
    deduped = (
        combined
        .sort_values('Weight', ascending=False)
        .drop_duplicates(['Player', 'Year_target'])
    )

    weighted_counts = (
        deduped
        .groupby(['Year_target', 'Team'])['Weight']
        .sum()
        .reset_index()
        .rename(columns={'Weight': 'allpro_weighted', 'Year_target': 'season'})
    )

    all_games.append(weighted_counts)

weighted_allpro_df = pd.concat(all_games, ignore_index=True)

print(weighted_allpro_df.head(10))
print(weighted_allpro_df[weighted_allpro_df['season'] == 2025].sort_values('allpro_weighted', ascending=False).head(10))

offense_df = allpro_df[allpro_df['Side'] == 'offense'].copy()
defense_df = allpro_df[allpro_df['Side'] == 'defense'].copy()

def build_weighted_allpro(df_ap):
    all_games = []
    for year in range(2006, 2026):
        curr = []
        for yrs_back, weight in zip([1, 2, 3], [4, 2, 1]):
            prev_year = year - yrs_back
            df_prev = df_ap[df_ap['Year'] == prev_year].copy()
            df_prev['Weight'] = weight
            df_prev['Year_target'] = year
            curr.append(df_prev)

        combined = pd.concat(curr)
        deduped = (
            combined
            .sort_values('Weight', ascending=False)
            .drop_duplicates(['Player', 'Year_target'])
        )
        weighted_counts = (
            deduped
            .groupby(['Year_target', 'Team'])['Weight']
            .sum()
            .reset_index()
            .rename(columns={'Weight': 'allpro_weighted', 'Year_target': 'season'})
        )
        all_games.append(weighted_counts)
    return pd.concat(all_games, ignore_index=True)

offense_weighted = build_weighted_allpro(offense_df)
defense_weighted = build_weighted_allpro(defense_df)

print("Offense weighted sample:")
print(offense_weighted[offense_weighted['season'] == 2025].sort_values('allpro_weighted', ascending=False).head(5))
print("\nDefense weighted sample:")
print(defense_weighted[defense_weighted['season'] == 2025].sort_values('allpro_weighted', ascending=False).head(5))

prev_year_counts = (
    allpro_df
    .assign(season=allpro_df['Year'] + 1)   # shift forward — 2024 all-pros apply to 2025 season
    .groupby(['season', 'Team', 'Side'])['Player']
    .nunique()
    .reset_index(name='allpro_prev_year')
)

prev_offense = prev_year_counts[prev_year_counts['Side'] == 'offense'].drop(columns='Side')
prev_defense = prev_year_counts[prev_year_counts['Side'] == 'defense'].drop(columns='Side')

print("Prev year offense sample (2025 season):")
print(prev_offense[prev_offense['season'] == 2025].sort_values('allpro_prev_year', ascending=False).head(5))

TARGET_SEASON = 2025   # match whatever season you're predicting

def merge_allpro(df, feat_df, feat_col, home_col, away_col):
    # Filter to target season and drop the season column — we don't need it after filtering
    lookup = (
        feat_df[feat_df['season'] == TARGET_SEASON]
        .drop(columns='season')   # ← this is the fix
    )

    # Home team
    df = df.merge(
        lookup.rename(columns={'Team': 'home_team', feat_col: home_col}),
        on='home_team', how='left'
    )
    # Away team
    df = df.merge(
        lookup.rename(columns={'Team': 'away_team', feat_col: away_col}),
        on='away_team', how='left'
    )
    df[home_col] = df[home_col].fillna(0)
    df[away_col] = df[away_col].fillna(0)
    return df

# Overall weighted
upcoming = merge_allpro(upcoming, weighted_allpro_df, 'allpro_weighted',
                        'home_allpro_last_3_years_weighted', 'away_allpro_last_3_years_weighted')

# Offense weighted
upcoming = merge_allpro(upcoming, offense_weighted, 'allpro_weighted',
                        'home_offense_allpro_3_years', 'away_offense_allpro_3_years')

# Defense weighted
upcoming = merge_allpro(upcoming, defense_weighted, 'allpro_weighted',
                        'home_defense_allpro_3_years', 'away_defense_allpro_3_years')

# Prev year offense
upcoming = merge_allpro(upcoming, prev_offense, 'allpro_prev_year',
                        'home_offense_allpro_prev_year', 'away_offense_allpro_prev_year')

# Prev year defense
upcoming = merge_allpro(upcoming, prev_defense, 'allpro_prev_year',
                        'home_defense_allpro_prev_year', 'away_defense_allpro_prev_year')

# Overall prev year
prev_overall = (
    allpro_df
    .assign(season=allpro_df['Year'] + 1)
    .groupby(['season', 'Team'])['Player']
    .nunique()
    .reset_index(name='allpro_prev_year')
)
upcoming = merge_allpro(upcoming, prev_overall, 'allpro_prev_year',
                        'home_allpro_prev_year', 'away_allpro_prev_year')

print(upcoming[['home_team', 'away_team',
                'home_allpro_last_3_years_weighted', 'away_allpro_last_3_years_weighted',
                'home_offense_allpro_3_years', 'away_offense_allpro_3_years',
                'home_defense_allpro_3_years', 'away_defense_allpro_3_years']].to_string())

upcoming['diff_allpro_last_3_years_weighted']   = upcoming['home_allpro_last_3_years_weighted']  - upcoming['away_allpro_last_3_years_weighted']
upcoming['diff_allpro_prev_year']               = upcoming['home_allpro_prev_year']               - upcoming['away_allpro_prev_year']
upcoming['allpro_diff_home_off_away_def_3_years']  = upcoming['home_offense_allpro_3_years']      - upcoming['away_defense_allpro_3_years']
upcoming['allpro_diff_home_def_away_off_3_years ']  = upcoming['home_defense_allpro_3_years']      - upcoming['away_offense_allpro_3_years']
upcoming['allpro_diff_home_off_away_def_prev_year'] = upcoming['home_offense_allpro_prev_year']   - upcoming['away_defense_allpro_prev_year']
upcoming['allpro_diff_home_def_away_off_prev_year'] = upcoming['home_defense_allpro_prev_year']   - upcoming['away_offense_allpro_prev_year']

print("Diff features:")
diff_cols = [c for c in upcoming.columns if 'diff' in c and 'allpro' in c]
print(upcoming[['home_team', 'away_team'] + diff_cols].to_string())

have    = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

"""## other feature wrangling"""

upcoming['is_playoff'] = upcoming['game_type'] != 'REG'

final_week_num = history[history['game_type'] == 'REG']['week'].max()
upcoming['is_final_week'] = (
    (upcoming['game_type'] == 'REG') &
    (upcoming['week'] == final_week_num)
)

# Build a lookup of who each team's QB was last week
home_qbs = history[['season', 'week', 'home_team', 'home_qb_name']].rename(
    columns={'home_team': 'team', 'home_qb_name': 'qb_name'}
)
away_qbs = history[['season', 'week', 'away_team', 'away_qb_name']].rename(
    columns={'away_team': 'team', 'away_qb_name': 'qb_name'}
)

team_qbs = pd.concat([home_qbs, away_qbs])
team_qbs = team_qbs.sort_values(['team', 'season', 'week'])

# Most recent QB per team from history
last_qb = (
    team_qbs
    .groupby('team')
    .last()
    .reset_index()
    [['team', 'qb_name']]
    .rename(columns={'qb_name': 'last_qb'})
)

# Merge onto upcoming
upcoming = upcoming.merge(
    last_qb.rename(columns={'team': 'home_team', 'last_qb': 'home_last_qb'}),
    on='home_team', how='left'
)
upcoming = upcoming.merge(
    last_qb.rename(columns={'team': 'away_team', 'last_qb': 'away_last_qb'}),
    on='away_team', how='left'
)

# Switch = QB this week is different from QB last week
upcoming['home_qb_switch'] = (
    upcoming['home_qb_name'] != upcoming['home_last_qb']
).fillna(False)
upcoming['away_qb_switch'] = (
    upcoming['away_qb_name'] != upcoming['away_last_qb']
).fillna(False)

# is_new is the same concept — your model has both
upcoming['is_home_qb_new'] = upcoming['home_qb_switch']
upcoming['is_away_qb_new'] = upcoming['away_qb_switch']

# Sanity check
print(upcoming[['home_team', 'away_team', 'home_qb_name', 'home_last_qb',
                'home_qb_switch', 'away_qb_switch']].to_string())

# Reuse long_df from the SOS step — it already has win/loss per team per game
# If you don't have it in memory, rebuild it quickly:
home_g = history[['season', 'week', 'home_team', 'home_score', 'away_score']].copy()
home_g.columns = ['season', 'week', 'team', 'team_score', 'opp_score']
away_g = history[['season', 'week', 'away_team', 'away_score', 'home_score']].copy()
away_g.columns = ['season', 'week', 'team', 'team_score', 'opp_score']

wins_df = pd.concat([home_g, away_g])
wins_df['team_win'] = (wins_df['team_score'] > wins_df['opp_score']).astype(int)
wins_df = wins_df.sort_values(['team', 'season', 'week'])

# Rolling 5-game win pct
wins_df['rolling_win_pct'] = (
    wins_df
    .groupby('team')['team_win']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

# Get most recent value per team
latest_win_pct = (
    wins_df
    .groupby('team')
    .last()
    .reset_index()
    [['team', 'rolling_win_pct']]
)

upcoming = upcoming.merge(
    latest_win_pct.rename(columns={'team': 'home_team', 'rolling_win_pct': 'home_rolling_win_pct'}),
    on='home_team', how='left'
)
upcoming = upcoming.merge(
    latest_win_pct.rename(columns={'team': 'away_team', 'rolling_win_pct': 'away_rolling_win_pct'}),
    on='away_team', how='left'
)

print(upcoming[['home_team', 'away_team', 'home_rolling_win_pct', 'away_rolling_win_pct']].to_string())

# Scoring diff — avg points scored vs avg points allowed (rolling 5 games)
home_g2 = history[['season', 'week', 'home_team', 'away_team',
                    'home_score', 'away_score', 'spread_line', 'result']].copy()
home_g2.columns = ['season', 'week', 'team', 'opp',
                   'team_score', 'opp_score', 'spread_line', 'result']
away_g2 = history[['season', 'week', 'away_team', 'home_team',
                    'away_score', 'home_score', 'spread_line', 'result']].copy()
away_g2.columns = ['season', 'week', 'team', 'opp',
                   'team_score', 'opp_score', 'spread_line', 'result']

scoring_df = pd.concat([home_g2, away_g2])
scoring_df = scoring_df.sort_values(['team', 'season', 'week'])

# Rolling avg points scored and allowed
scoring_df['rolling_scored']  = scoring_df.groupby('team')['team_score'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)
scoring_df['rolling_allowed'] = scoring_df.groupby('team')['opp_score'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)

# Cover rate — did team cover the spread (for home perspective, result > spread means home covered)
scoring_df['covered'] = (scoring_df['result'] > scoring_df['spread_line']).astype(int)
scoring_df['rolling_cover_rate'] = scoring_df.groupby('team')['covered'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)

latest_scoring = (
    scoring_df.groupby('team').last().reset_index()
    [['team', 'rolling_scored', 'rolling_allowed', 'rolling_cover_rate']]
)

# League rolling avg absolute margin by week
league_margin = (
    history.groupby('week')['result']
    .apply(lambda x: x.abs().mean())
    .reset_index()
    .rename(columns={'result': 'league_rolling_avg_abs_margin_by_week'})
)
# Use the most recent week's value
latest_league_margin = league_margin.iloc[-1]['league_rolling_avg_abs_margin_by_week']
upcoming['league_rolling_avg_abs_margin_by_week'] = latest_league_margin

# Merge scoring stats
upcoming = upcoming.merge(
    latest_scoring.rename(columns={
        'team': 'home_team',
        'rolling_scored': 'home_rolling_scored',
        'rolling_allowed': 'home_rolling_allowed',
        'rolling_cover_rate': 'home_rolling_cover_rate'
    }), on='home_team', how='left'
)
upcoming = upcoming.merge(
    latest_scoring.rename(columns={
        'team': 'away_team',
        'rolling_scored': 'away_rolling_scored',
        'rolling_allowed': 'away_rolling_allowed',
        'rolling_cover_rate': 'away_rolling_cover_rate'
    }), on='away_team', how='left'
)

# Compute diff features
upcoming['scoring_diff']         = upcoming['home_rolling_scored']  - upcoming['away_rolling_scored']
upcoming['scoring_diff_reverse'] = upcoming['away_rolling_scored']  - upcoming['home_rolling_scored']
upcoming['cover_rate_diff']      = upcoming['home_rolling_cover_rate'] - upcoming['away_rolling_cover_rate']

print(upcoming[['home_team', 'away_team', 'scoring_diff', 'cover_rate_diff']].to_string())

# These all come from pbp_rp which you already pulled

# Sacks — a sack is when epa < 0 and it's a pass play with a sack recorded
sack_df = pbp_rp[pbp_rp['sack'] == 1].copy()
sacks_per_game = (
    sack_df.groupby(['game_id', 'defteam'])
    .size().reset_index(name='sacks')
    .rename(columns={'defteam': 'team'})
)
sacks_per_game = sacks_per_game.merge(
    schedule[['game_id', 'week', 'season']], on='game_id', how='left'
)
sacks_per_game = sacks_per_game.sort_values(['team', 'season', 'week'])
sacks_per_game['rolling_sacks'] = sacks_per_game.groupby('team')['sacks'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)
latest_sacks = sacks_per_game.groupby('team').last().reset_index()[['team', 'rolling_sacks']]

# Turnovers — interceptions + fumbles lost
pbp_rp['turnover'] = ((pbp_rp['interception'] == 1) | (pbp_rp['fumble_lost'] == 1)).astype(int)
to_df = (
    pbp_rp.groupby(['game_id', 'posteam'])['turnover']
    .sum().reset_index().rename(columns={'posteam': 'team'})
)
to_df = to_df.merge(schedule[['game_id', 'week', 'season']], on='game_id', how='left')
to_df = to_df.sort_values(['team', 'season', 'week'])
to_df['rolling_turnovers'] = to_df.groupby('team')['turnover'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)
latest_to = to_df.groupby('team').last().reset_index()[['team', 'rolling_turnovers']]

# Third down conversion rate
pbp_rp['third_down_att'] = (pbp_rp['down'] == 3).astype(int)
pbp_rp['third_down_conv'] = ((pbp_rp['down'] == 3) & (pbp_rp['first_down'] == 1)).astype(int)
third_df = (
    pbp_rp.groupby(['game_id', 'posteam'])
    .agg(third_att=('third_down_att', 'sum'), third_conv=('third_down_conv', 'sum'))
    .reset_index().rename(columns={'posteam': 'team'})
)
third_df['third_down_rate'] = third_df['third_conv'] / third_df['third_att'].replace(0, 1)
third_df = third_df.merge(schedule[['game_id', 'week', 'season']], on='game_id', how='left')
third_df = third_df.sort_values(['team', 'season', 'week'])
third_df['rolling_third_down'] = third_df.groupby('team')['third_down_rate'].transform(
    lambda x: x.shift(1).rolling(5, min_periods=1).mean()
)
latest_third = third_df.groupby('team').last().reset_index()[['team', 'rolling_third_down']]

# Merge all onto upcoming
for lookup, home_col, away_col in [
    (latest_sacks,  'home_rolling_sacks',      'away_rolling_sacks'),
    (latest_to,     'home_rolling_turnovers',   'away_rolling_turnovers'),
    (latest_third,  'home_rolling_third_down',  'away_rolling_third_down'),
]:
    upcoming = upcoming.merge(
        lookup.rename(columns={'team': 'home_team', lookup.columns[1]: home_col}),
        on='home_team', how='left'
    )
    upcoming = upcoming.merge(
        lookup.rename(columns={'team': 'away_team', lookup.columns[1]: away_col}),
        on='away_team', how='left'
    )

# Diff features
upcoming['sack_diff']              = upcoming['home_rolling_sacks']      - upcoming['away_rolling_sacks']
upcoming['sack_diff_reverse']      = upcoming['away_rolling_sacks']      - upcoming['home_rolling_sacks']
upcoming['turnover_diff']          = upcoming['home_rolling_turnovers']  - upcoming['away_rolling_turnovers']
upcoming['turnover_diff_reverse']  = upcoming['away_rolling_turnovers']  - upcoming['home_rolling_turnovers']
upcoming['third_down_diff']        = upcoming['home_rolling_third_down'] - upcoming['away_rolling_third_down']
upcoming['third_down_diff_reverse']= upcoming['away_rolling_third_down'] - upcoming['home_rolling_third_down']

print(upcoming[['home_team', 'away_team', 'sack_diff', 'turnover_diff', 'third_down_diff']].to_string())

have    = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

pass_plays = pbp_rp[
    (pbp_rp['play_type'] == 'pass') &
    (pbp_rp['passer_player_name'].notna())
].copy()

print(pbp_rp.shape)
print(pbp_rp['season'].unique())

raw_pbp = nfl.load_pbp([2024, 2025])
pbp = raw_pbp.to_pandas()

pbp_rp = pbp[
    pbp['play_type'].isin(['run', 'pass']) &
    pbp['posteam'].notna() &
    pbp['defteam'].notna()
].copy()

print(pbp_rp.shape)
print(pbp_rp['season'].unique())

# Cell 1 - filter to pass plays
pass_plays = pbp_rp[
    (pbp_rp['play_type'] == 'pass') &
    (pbp_rp['passer_player_name'].notna())
].copy()

# Cell 2 - aggregate per QB per season
qb_stats = (
    pass_plays
    .groupby(['season', 'posteam', 'passer_player_name'])
    .agg(
        attempts    = ('pass_attempt',   'sum'),
        completions = ('complete_pass',  'sum'),
        yards       = ('passing_yards',  'sum'),
        tds         = ('pass_touchdown', 'sum'),
        ints        = ('interception',   'sum')
    )
    .reset_index()
)

qb_stats = qb_stats[qb_stats['attempts'] >= 100]

# Cell 3 - apply passer rating formula
def passer_rating(row):
    a = max(0, min(((row['completions'] / row['attempts']) - 0.3) * 5,   2.375))
    b = max(0, min(((row['yards']       / row['attempts']) - 3)  * 0.25, 2.375))
    c = max(0, min(  row['tds']         / row['attempts']  * 20,         2.375))
    d = max(0, min(2.375 - (row['ints'] / row['attempts']  * 25),        2.375))
    return ((a + b + c + d) / 6) * 100

qb_stats['passer_rating'] = qb_stats.apply(passer_rating, axis=1)

# Cell 4 - best QB per team per season (starter = most attempts)
best_qb = (
    qb_stats
    .sort_values('attempts', ascending=False)
    .groupby(['season', 'posteam'])
    .first()
    .reset_index()
    [['season', 'posteam', 'passer_player_name', 'passer_rating']]
)

print(f"Seasons covered: {best_qb['season'].min()} - {best_qb['season'].max()}")
print(best_qb[best_qb['season'] == 2024].sort_values('passer_rating', ascending=False))

PREV_SEASON = TARGET_SEASON - 1   # 2024

pr_prev = best_qb[best_qb['season'] == PREV_SEASON][['posteam', 'passer_rating']].copy()

upcoming = upcoming.merge(
    pr_prev.rename(columns={'posteam': 'home_team', 'passer_rating': 'home_qbr_prev_year'}),
    on='home_team', how='left'
)
upcoming = upcoming.merge(
    pr_prev.rename(columns={'posteam': 'away_team', 'passer_rating': 'away_qbr_prev_year'}),
    on='away_team', how='left'
)

median_pr = pr_prev['passer_rating'].median()
upcoming['home_qbr_prev_year'] = upcoming['home_qbr_prev_year'].fillna(median_pr)
upcoming['away_qbr_prev_year'] = upcoming['away_qbr_prev_year'].fillna(median_pr)
upcoming['diff_qbr_prev_year'] = upcoming['home_qbr_prev_year'] - upcoming['away_qbr_prev_year']

print(upcoming[['home_team', 'away_team',
                'home_qbr_prev_year', 'away_qbr_prev_year',
                'diff_qbr_prev_year']].to_string())

have    = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

raw_inj = nfl.load_injuries(seasons=[2025])
inj_df = raw_inj.to_pandas()

print(inj_df.shape)
print(inj_df.columns.tolist())
print(inj_df['report_status'].value_counts())

TARGET_WEEK = upcoming['week'].iloc[0]   # whatever week you're predicting

# Only count players listed as Out
inj_status = inj_df[
    (inj_df['report_status'] == 'Out') &
    (inj_df['week'] == TARGET_WEEK)
].copy()

injuries_by_team = (
    inj_status
    .groupby(['season', 'week', 'team'])
    .agg(injured_player_count=('full_name', 'count'))
    .reset_index()
)

# Merge home
upcoming = upcoming.merge(
    injuries_by_team.rename(columns={
        'team': 'home_team',
        'injured_player_count': 'home_injured_count'
    }).drop(columns=['season', 'week']),
    on='home_team', how='left'
)

# Merge away
upcoming = upcoming.merge(
    injuries_by_team.rename(columns={
        'team': 'away_team',
        'injured_player_count': 'away_injured_count'
    }).drop(columns=['season', 'week']),
    on='away_team', how='left'
)

upcoming[['home_injured_count', 'away_injured_count']] = (
    upcoming[['home_injured_count', 'away_injured_count']].fillna(0).astype(int)
)
upcoming['diff_injured_count'] = upcoming['home_injured_count'] - upcoming['away_injured_count']

print(upcoming[['home_team', 'away_team',
                'home_injured_count', 'away_injured_count',
                'diff_injured_count']].to_string())

# Out players only
inj_allpro_df = inj_df[
    (inj_df['report_status'] == 'Out') &
    (inj_df['week'] == TARGET_WEEK)
].copy()
inj_allpro_df['season'] = inj_allpro_df['season'].astype(int)
inj_allpro_df['week']   = inj_allpro_df['week'].astype(int)

# Build weighted all-pro history (same 4/2/1/0.5 weights as notebook)
allpro_history = []
for yrs_back, weight in zip([0, 1, 2, 3], [4, 2, 1, 0.5]):
    temp = allpro_df.copy()
    temp['season'] = temp['Year'] + yrs_back
    temp['weight'] = weight
    allpro_history.append(temp)

allpro_weighted_hist = pd.concat(allpro_history)

# Merge to find injured players who are/were all-pros
inj_allpro_df = inj_allpro_df.merge(
    allpro_weighted_hist[['Player', 'season', 'Team', 'weight']],
    left_on=['full_name', 'season'],
    right_on=['Player', 'season'],
    how='left'
)

# Only keep rows where player was an all-pro
inj_allpro_df = inj_allpro_df[inj_allpro_df['weight'].notnull()]

# Sum weights per team per week
injured_allpro_weighted = (
    inj_allpro_df
    .groupby(['season', 'week', 'team'])['weight']
    .sum()
    .reset_index()
    .rename(columns={'weight': 'injured_allpro_weighted_count'})
)

# Merge home
upcoming = upcoming.merge(
    injured_allpro_weighted.rename(columns={'team': 'home_team'}).drop(columns=['season', 'week']),
    on='home_team', how='left'
).rename(columns={'injured_allpro_weighted_count': 'home_injured_allpro_weighted_count'})

# Merge away
upcoming = upcoming.merge(
    injured_allpro_weighted.rename(columns={'team': 'away_team'}).drop(columns=['season', 'week']),
    on='away_team', how='left'
).rename(columns={'injured_allpro_weighted_count': 'away_injured_allpro_weighted_count'})

upcoming[['home_injured_allpro_weighted_count', 'away_injured_allpro_weighted_count']] = (
    upcoming[['home_injured_allpro_weighted_count', 'away_injured_allpro_weighted_count']].fillna(0)
)

# Active allpro weighted = total weighted allpro - injured weighted allpro
upcoming['home_active_allpro_weighted'] = (
    upcoming['home_allpro_last_3_years_weighted'] - upcoming['home_injured_allpro_weighted_count']
)
upcoming['away_active_allpro_weighted'] = (
    upcoming['away_allpro_last_3_years_weighted'] - upcoming['away_injured_allpro_weighted_count']
)
upcoming['diff_active_allpro_weighted'] = (
    upcoming['home_active_allpro_weighted'] - upcoming['away_active_allpro_weighted']
)

print(upcoming[['home_team', 'away_team',
                'diff_active_allpro_weighted']].to_string())

# Prev year allpros shifted to current season
allpro_prev_year_df = allpro_df.copy()
allpro_prev_year_df['season'] = allpro_prev_year_df['Year'] + 1

inj_prev_df = inj_df[
    (inj_df['report_status'] == 'Out') &
    (inj_df['week'] == TARGET_WEEK)
].copy()
inj_prev_df['season'] = inj_prev_df['season'].astype(int)

inj_prev_df = inj_prev_df.merge(
    allpro_prev_year_df[['Player', 'season', 'Team']],
    left_on=['full_name', 'season'],
    right_on=['Player', 'season'],
    how='left'
)
inj_prev_df['is_prev_year_allpro'] = inj_prev_df['Team'].notnull().astype(int)

injured_allpro_prev = (
    inj_prev_df[inj_prev_df['is_prev_year_allpro'] == 1]
    .groupby(['season', 'week', 'team'])
    .agg(injured_allpro_prev_year_count=('full_name', 'count'))
    .reset_index()
)

# Merge home
upcoming = upcoming.merge(
    injured_allpro_prev.rename(columns={'team': 'home_team'}).drop(columns=['season', 'week']),
    on='home_team', how='left'
).rename(columns={'injured_allpro_prev_year_count': 'home_injured_allpro_prev_year_count'})

# Merge away
upcoming = upcoming.merge(
    injured_allpro_prev.rename(columns={'team': 'away_team'}).drop(columns=['season', 'week']),
    on='away_team', how='left'
).rename(columns={'injured_allpro_prev_year_count': 'away_injured_allpro_prev_year_count'})

upcoming[['home_injured_allpro_prev_year_count', 'away_injured_allpro_prev_year_count']] = (
    upcoming[['home_injured_allpro_prev_year_count', 'away_injured_allpro_prev_year_count']].fillna(0).astype(int)
)

upcoming['home_active_allpro_prev_year'] = (
    upcoming['home_allpro_prev_year'] - upcoming['home_injured_allpro_prev_year_count']
)
upcoming['away_active_allpro_prev_year'] = (
    upcoming['away_allpro_prev_year'] - upcoming['away_injured_allpro_prev_year_count']
)
upcoming['diff_active_allpro_prev_year'] = (
    upcoming['home_active_allpro_prev_year'] - upcoming['away_active_allpro_prev_year']
)

print(upcoming[['home_team', 'away_team', 'diff_active_allpro_prev_year']].to_string())

import numpy as np

# Pull extended schedule history for coach win pct
raw_coach = nfl.load_schedules(list(range(1999, 2026)))
coach_df = raw_coach.to_pandas()

# Reshape to long format — one row per team per game
home_c = coach_df[['game_id', 'season', 'week', 'home_team', 'away_team',
                    'home_score', 'away_score', 'home_coach']].copy()
home_c.rename(columns={
    'home_team': 'team', 'away_team': 'opponent',
    'home_score': 'team_score', 'away_score': 'opponent_score',
    'home_coach': 'coach'
}, inplace=True)

away_c = coach_df[['game_id', 'season', 'week', 'away_team', 'home_team',
                    'away_score', 'home_score', 'away_coach']].copy()
away_c.rename(columns={
    'away_team': 'team', 'home_team': 'opponent',
    'away_score': 'team_score', 'home_score': 'opponent_score',
    'away_coach': 'coach'
}, inplace=True)

team_games_df = pd.concat([home_c, away_c], ignore_index=True)
team_games_df = team_games_df.dropna(subset=['team_score', 'opponent_score'])
team_games_df['win'] = (team_games_df['team_score'] > team_games_df['opponent_score']).astype(int)

# Cumulative win % per coach going INTO each game (shift so no leakage)
def compute_cumulative_stats(group):
    group = group.sort_values(['season', 'week', 'game_id']).copy()
    group['cumulative_wins']  = group['win'].cumsum().shift(fill_value=0)
    group['cumulative_games'] = group['win'].expanding().count().shift(fill_value=0)
    return group

team_games_df = team_games_df.groupby('coach', group_keys=False).apply(compute_cumulative_stats)

team_games_df['coach_win_pct_prior'] = (
    team_games_df['cumulative_wins'] /
    team_games_df['cumulative_games'].replace(0, np.nan)
).fillna(0).round(3)

coach_win_pct_df = team_games_df[['game_id', 'team', 'coach', 'coach_win_pct_prior']]

# Merge onto upcoming using game_id
upcoming = upcoming.merge(
    coach_win_pct_df.rename(columns={
        'team': 'home_team',
        'coach_win_pct_prior': 'home_coach_win_pct_prior'
    })[['game_id', 'home_team', 'home_coach_win_pct_prior']],
    on=['game_id', 'home_team'], how='left'
)

upcoming = upcoming.merge(
    coach_win_pct_df.rename(columns={
        'team': 'away_team',
        'coach_win_pct_prior': 'away_coach_win_pct_prior'
    })[['game_id', 'away_team', 'away_coach_win_pct_prior']],
    on=['game_id', 'away_team'], how='left'
)

print(upcoming[['home_team', 'away_team',
                'home_coach_win_pct_prior',
                'away_coach_win_pct_prior']].to_string())

have    = [f for f in model_features if f in upcoming.columns]
missing = [f for f in model_features if f not in upcoming.columns]

print(f"Have: {len(have)}/79")
print(f"\nStill missing ({len(missing)}):")
for f in missing:
    print(f"  - {f}")

"""## running model"""

# These are the exact columns the model was trained on
feature_cols = cat_cols + num_cols  # from step 1 at the very beginning

# Pull only those columns from upcoming
X = upcoming[feature_cols].copy()

print(X.shape)        # should be (14, 79) — 14 games, 79 features
print(X.isnull().sum().sum())   # should be 0 — no nulls

pipeline = res['pipeline']

predictions = pipeline.predict(X)

print(predictions)

"""## mini eval"""

results = upcoming[['game_id', 'home_team', 'away_team',
                     'gameday', 'spread_line']].copy()

results['predicted_margin'] = predictions.round(1)

# Model edge = how much the model disagrees with the spread
# Positive = model thinks home covers, negative = model thinks away covers
results['model_edge'] = (results['predicted_margin'] - results['spread_line']).round(1)

# Recommendation
def recommend(row):
    if row['model_edge'] > 0:
        return f"BET HOME ({row['home_team']})"
    elif row['model_edge'] < 0:
        return f"BET AWAY ({row['away_team']})"
    else:
        return "PASS"

results['recommendation'] = results.apply(recommend, axis=1)

# Sort by strongest edge first
results = results.sort_values('model_edge', key=abs, ascending=False)

print(results.to_string(index=False))

EDGE_THRESHOLD = 3.0   # only show games where model disagrees with spread by 1+ pts

strong_edges = results[results['model_edge'].abs() >= EDGE_THRESHOLD]

print(f"Games above threshold: {len(strong_edges)}/{len(results)}")
print()
print(strong_edges[['home_team', 'away_team', 'spread_line',
                     'predicted_margin', 'model_edge',
                     'recommendation']].to_string(index=False))

# Actual results are already in your schedule DataFrame
actual = schedule[
    (schedule['season'] == 2025) &
    (schedule['week'] == 10)
][['game_id', 'home_team', 'away_team', 'home_score',
   'away_score', 'spread_line', 'result']].copy()

# result = home score - away score (actual margin)
actual = actual.rename(columns={'result': 'actual_margin'})

print(actual.to_string(index=False))

EDGE_THRESHOLD = 3.0   # only show games where model disagrees with spread by 1+ pts

strong_edges = results[results['model_edge'].abs() >= EDGE_THRESHOLD]

print(f"Games above threshold: {len(strong_edges)}/{len(results)}")
print()
print(strong_edges[['home_team', 'away_team', 'spread_line',
                     'predicted_margin', 'model_edge',
                     'recommendation']].to_string(index=False))

eval_df = results.merge(
    actual[['game_id', 'actual_margin', 'home_score', 'away_score']],
    on='game_id', how='left'
)

# Did the home team actually cover the spread?
# actual_margin > spread_line means home covered
eval_df['home_covered'] = eval_df['actual_margin'] > eval_df['spread_line']

# Did the model call it correctly?
eval_df['model_correct'] = (
    (eval_df['model_edge'] > 0) == eval_df['home_covered']
)

# Prediction error — how far off was the margin prediction
eval_df['margin_error'] = (
    eval_df['predicted_margin'] - eval_df['actual_margin']
).abs().round(1)

print(eval_df[['home_team', 'away_team', 'spread_line',
               'predicted_margin', 'actual_margin',
               'model_edge', 'home_covered',
               'model_correct', 'margin_error']].to_string(index=False))

"""8/14 on all of week 10, 2/3 on large diff bets"""

total         = len(eval_df)
correct       = eval_df['model_correct'].sum()
avg_error     = eval_df['margin_error'].mean()

# Evaluate only games above your edge threshold
strong        = eval_df[eval_df['model_edge'].abs() >= EDGE_THRESHOLD]
strong_correct = strong['model_correct'].sum()
strong_total   = len(strong)

print("=" * 40)
print(f"WEEK 10 MODEL EVALUATION")
print("=" * 40)
print(f"Overall ATS record:     {correct}/{total} ({correct/total*100:.1f}%)")
print(f"Avg margin error:       {avg_error:.1f} pts")
print(f"Strong edge ATS record: {strong_correct}/{strong_total} ({strong_correct/strong_total*100:.1f}% at edge >= {EDGE_THRESHOLD})")
print()
print("GAME BY GAME:")
for _, row in eval_df.sort_values('model_edge', key=abs, ascending=False).iterrows():
    result_str = "✅" if row['model_correct'] else "❌"
    print(f"{result_str} {row['away_team']} @ {row['home_team']} | "
          f"Spread: {row['spread_line']:+.1f} | "
          f"Predicted: {row['predicted_margin']:+.1f} | "
          f"Actual: {row['actual_margin']:+.1f} | "
          f"Edge: {row['model_edge']:+.1f}")

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1 — predicted vs actual margin
ax1 = axes[0]
colors = ['green' if c else 'red' for c in eval_df['model_correct']]
ax1.scatter(eval_df['actual_margin'], eval_df['predicted_margin'],
            c=colors, s=100, alpha=0.8, edgecolors='black', linewidths=0.5)
ax1.axhline(0, color='gray', linestyle='--', alpha=0.5)
ax1.axvline(0, color='gray', linestyle='--', alpha=0.5)
ax1.plot([-30, 30], [-30, 30], color='blue', linestyle='--',
         alpha=0.3, label='Perfect prediction')
for _, row in eval_df.iterrows():
    ax1.annotate(f"{row['home_team']}",
                 (row['actual_margin'], row['predicted_margin']),
                 fontsize=7, ha='left', va='bottom')
ax1.set_xlabel('Actual Margin')
ax1.set_ylabel('Predicted Margin')
ax1.set_title('Predicted vs Actual Margin\n(green = correct ATS, red = wrong)')
ax1.legend()

# Plot 2 — model edge vs actual edge (did model identify the right side?)
eval_df['actual_edge'] = eval_df['actual_margin'] - eval_df['spread_line']
ax2 = axes[1]
ax2.scatter(eval_df['model_edge'], eval_df['actual_edge'],
            c=colors, s=100, alpha=0.8, edgecolors='black', linewidths=0.5)
ax2.axhline(0, color='gray', linestyle='--', alpha=0.5)
ax2.axvline(0, color='gray', linestyle='--', alpha=0.5)
for _, row in eval_df.iterrows():
    ax2.annotate(f"{row['home_team']}",
                 (row['model_edge'], row['actual_edge']),
                 fontsize=7, ha='left', va='bottom')
ax2.set_xlabel('Model Edge (predicted - spread)')
ax2.set_ylabel('Actual Edge (actual - spread)')
ax2.set_title('Model Edge vs Actual Edge\n(Q1 & Q3 = correct side, Q2 & Q4 = wrong side)')

plt.tight_layout()
plt.show()

"""## logging"""

import os
from datetime import datetime

TRACKER_PATH = '/content/drive/MyDrive/BettingEdgeContinued/predictions_tracker.csv'

# Build the predictions log for this week
log = results[['game_id', 'home_team', 'away_team', 'gameday',
               'spread_line', 'predicted_margin',
               'model_edge', 'recommendation']].copy()

log['season']        = TARGET_SEASON
log['week']          = TARGET_WEEK
log['logged_at']     = datetime.now().strftime('%Y-%m-%d %H:%M')
log['actual_margin'] = None   # filled in after games are played
log['home_covered']  = None
log['model_correct'] = None

# Append to tracker — create it if it doesn't exist yet
if os.path.exists(TRACKER_PATH):
    existing = pd.read_csv(TRACKER_PATH)

    # Don't double-log the same week
    already_logged = (
        (existing['season'] == TARGET_SEASON) &
        (existing['week']   == TARGET_WEEK)
    ).any()

    if already_logged:
        print(f"⚠️  Week {TARGET_WEEK} already logged. Skipping.")
    else:
        tracker = pd.concat([existing, log], ignore_index=True)
        tracker.to_csv(TRACKER_PATH, index=False)
        print(f"✅ Logged {len(log)} games for week {TARGET_WEEK}")
else:
    log.to_csv(TRACKER_PATH, index=False)
    print(f"✅ Created tracker and logged {len(log)} games for week {TARGET_WEEK}")

def update_results(season, week):
    if not os.path.exists(TRACKER_PATH):
        print("No tracker found. Run predictions first.")
        return

    tracker = pd.read_csv(TRACKER_PATH)

    # Pull actual results — already a pandas DataFrame
    raw = nfl.load_schedules([season])
    actual_schedule = raw.to_pandas() if hasattr(raw, 'to_pandas') else pd.DataFrame(raw)

    actual = actual_schedule[
        (actual_schedule['season'] == season) &
        (actual_schedule['week']   == week)
    ][['game_id', 'result']].rename(columns={'result': 'actual_margin'})

    # Get the rows to update
    mask = (tracker['season'] == season) & (tracker['week'] == week)
    indices = tracker[mask].index

    # Merge actual results in
    rows = tracker.loc[indices].copy()
    rows = rows.merge(actual, on='game_id', how='left', suffixes=('_old', '_new'))

    # Fill in the new columns
    rows['actual_margin'] = rows['actual_margin_new']
    rows['home_covered']  = rows['actual_margin'] > rows['spread_line']
    rows['model_correct'] = (rows['model_edge'] > 0) == rows['home_covered']
    rows = rows.drop(columns=['actual_margin_old', 'actual_margin_new'], errors='ignore')

    # Write back to tracker
    tracker.loc[indices, 'actual_margin'] = rows['actual_margin'].values
    tracker.loc[indices, 'home_covered']  = rows['home_covered'].astype(int).values
    tracker.loc[indices, 'model_correct'] = rows['model_correct'].astype(int).values
    tracker.to_csv(TRACKER_PATH, index=False)

    # Summary
    correct = rows['model_correct'].sum()
    total   = len(rows)
    print(f"✅ Week {week} results updated")
    print(f"   ATS record: {correct}/{total} ({correct/total*100:.1f}%)")
    print()
    print(rows[['home_team', 'away_team', 'spread_line',
                'predicted_margin', 'actual_margin',
                'model_edge', 'model_correct']].to_string(index=False))

update_results(TARGET_SEASON, TARGET_WEEK)

def season_summary(season):
    if not os.path.exists(TRACKER_PATH):
        print("No tracker found.")
        return

    tracker = pd.read_csv(TRACKER_PATH)
    df = tracker[
        (tracker['season'] == season) &
        (tracker['actual_margin'].notna())
    ].copy()

    if df.empty:
        print("No completed games in tracker yet.")
        return

    total    = len(df)
    correct  = df['model_correct'].sum()
    avg_edge = df['model_edge'].abs().mean()
    avg_err  = (df['predicted_margin'] - df['actual_margin']).abs().mean()

    print("=" * 45)
    print(f"  SEASON {season} SUMMARY")
    print("=" * 45)
    print(f"  Weeks tracked:       {df['week'].nunique()}")
    print(f"  Total games:         {total}")
    print(f"  ATS record:          {int(correct)}-{total - int(correct)}")
    print(f"  ATS win rate:        {correct/total*100:.1f}%")
    print(f"  Avg model edge:      {avg_edge:.1f} pts")
    print(f"  Avg margin error:    {avg_err:.1f} pts")
    print()

    # Breakdown by edge threshold
    print("  Win rate by edge threshold:")
    for threshold in [0.5, 1.0, 1.5, 2.0, 3.0]:
        subset = df[df['model_edge'].abs() >= threshold]
        if len(subset) == 0:
            continue
        w = subset['model_correct'].sum()
        t = len(subset)
        print(f"    Edge >= {threshold}: {int(w)}/{t} ({w/t*100:.1f}%)")

    print()

    # Week by week record
    print("  Week by week:")
    weekly = df.groupby('week').agg(
        games     = ('model_correct', 'count'),
        correct   = ('model_correct', 'sum')
    )
    weekly['win_pct'] = (weekly['correct'] / weekly['games'] * 100).round(1)
    for week, row in weekly.iterrows():
        bar = "█" * int(row['correct']) + "░" * int(row['games'] - row['correct'])
        print(f"    Week {week:>2}: {bar}  {int(row['correct'])}/{int(row['games'])} ({row['win_pct']}%)")

season_summary(TARGET_SEASON)

"""## adding other weeks in?"""

if __name__ == '__main__':

    if MODE == 'monday':
        # 1. Fill in last week's results
        if PREV_WEEK:
            update_results(TARGET_SEASON, PREV_WEEK)

        # 2. Generate early predictions for upcoming week
        if TARGET_WEEK:
            print(f"\nGenerating early predictions for week {TARGET_WEEK}...")
            # --- your full feature pipeline runs here ---
            # results = <your prediction code>
            log_predictions(results, TARGET_SEASON, TARGET_WEEK, mode='monday')

    elif MODE == 'thursday':
        # Refresh predictions with updated injury reports
        if TARGET_WEEK:
            print(f"\nRefreshing week {TARGET_WEEK} predictions with Thursday injury data...")
            # --- your full feature pipeline runs here ---
            # results = <your prediction code>
            log_predictions(results, TARGET_SEASON, TARGET_WEEK, mode='thursday')

    elif MODE == 'sunday':
        # Final predictions before kickoff
        if TARGET_WEEK:
            print(f"\nFinal predictions for week {TARGET_WEEK}...")
            # --- your full feature pipeline runs here ---
            # results = <your prediction code>
            log_predictions(results, TARGET_SEASON, TARGET_WEEK, mode='sunday')

import os
import pandas as pd
import numpy as np
from datetime import datetime

TRACKER_PATH = '/content/drive/MyDrive/BettingEdgeContinued/predictions_tracker.csv'
TARGET_SEASON = 2025
BACKFILL_WEEKS = range(10, 18)   # weeks 10 through 17

# Start fresh
if os.path.exists(TRACKER_PATH):
    os.remove(TRACKER_PATH)
    print("Cleared old tracker")

# Pull full season schedule once — reused every iteration
raw_schedule = nfl.load_schedules([TARGET_SEASON])
full_schedule = raw_schedule.to_pandas() if hasattr(raw_schedule, 'to_pandas') else pd.DataFrame(raw_schedule)
full_schedule['season'] = full_schedule['season'].astype(int)
full_schedule['week']   = full_schedule['week'].astype(int)

print(f"Schedule loaded: {full_schedule.shape}")
print(f"Weeks to backfill: {list(BACKFILL_WEEKS)}\n")

# Pull PBP once for the full season — reused every iteration
print("Pulling PBP data (this takes ~60s)...")
raw_pbp = nfl.load_pbp([TARGET_SEASON, TARGET_SEASON - 1])
pbp = raw_pbp.to_pandas() if hasattr(raw_pbp, 'to_pandas') else pd.DataFrame(raw_pbp)
pbp_rp = pbp[
    pbp['play_type'].isin(['run', 'pass']) &
    pbp['posteam'].notna() &
    pbp['defteam'].notna()
].copy()

print(f"PBP loaded: {pbp_rp.shape}")
print(f"Seasons in PBP: {pbp_rp['season'].unique()}")

# Load static data once — reused every iteration
allpro_df = pd.read_csv('/content/drive/MyDrive/BettingEdgeContinued/nfl_allpro_1997_2025.csv')
allpro_df = allpro_df[allpro_df['Team'] != '2TM'].copy()

team_map = {
    'STL': 'LA', 'LAR': 'LA', 'OAK': 'LV', 'LVR': 'LV',
    'SD': 'LAC', 'SDG': 'LAC', 'NWE': 'NE', 'KAN': 'KC',
    'GNB': 'GB', 'NOR': 'NO', 'TAM': 'TB', 'SFO': 'SF', 'JAX': 'JAC'
}
allpro_df['Team'] = allpro_df['Team'].replace(team_map)

# Load model
from dataclasses import dataclass, field
from typing import Tuple, Dict, Any
import joblib

@dataclass(frozen=True)
class FinalCfg:
    test_size: float = 0.2
    random_state: int = 42
    oof_splits: int = 5
    weight_win: float = 2.0
    weight_loss: float = 1.0
    drop_non_features: Tuple[str, ...] = ('game_id','home_team','away_team','season','week')
    categorical_cols: Tuple[str, ...] = ('roof','surface')
    boolean_cols: Tuple[str, ...] = (
        'is_playoff','is_final_week','home_qb_switch','away_qb_switch',
        'is_home_qb_new','is_away_qb_new'
    )
    base_xgb_params: Dict[str, Any] = field(default_factory=lambda: dict(
        n_estimators=500, max_depth=3, learning_rate=0.01, min_child_weight=3,
        subsample=0.6, colsample_bytree=0.6, reg_alpha=1.0, reg_lambda=3.0,
        objective='reg:squarederror', random_state=42, tree_method='hist', n_jobs=1
    ))

res      = joblib.load('/content/drive/MyDrive/BettingEdgeContinued/fantasy_model.pkl')
pipeline = res['pipeline']
pre      = pipeline.named_steps['preprocessor']
cat_cols = list(pre.transformers_[0][2])
num_cols = list(pre.transformers_[1][2])
model_features = cat_cols + num_cols

print(f"Model loaded — expects {len(model_features)} features")

def build_features_for_week(target_week, target_season, full_schedule, pbp_rp, allpro_df):

    # ── Split schedule ────────────────────────────────────────────────────────
    history = full_schedule[
        (full_schedule['week'] < target_week) &
        (full_schedule['season'] == target_season) &
        (full_schedule['result'].notna())
    ].copy()

    upcoming = full_schedule[
        (full_schedule['week'] == target_week) &
        (full_schedule['season'] == target_season)
    ].copy()

    if upcoming.empty:
        return None

    # ── Group 1 — basic schedule features ────────────────────────────────────
    upcoming['temp'] = upcoming['temp'].fillna(72)
    upcoming['wind'] = upcoming['wind'].fillna(0)
    upcoming['is_playoff'] = upcoming['game_type'] != 'REG'

    final_week_num = history[history['game_type'] == 'REG']['week'].max()
    upcoming['is_final_week'] = (
        (upcoming['game_type'] == 'REG') &
        (upcoming['week'] == final_week_num)
    )

    # ── Group 2 — rolling PBP stats ───────────────────────────────────────────
    pbp_season = pbp_rp[pbp_rp['season'] == target_season].copy()

    # ✅ FIX: only keep week to avoid collisions
    week_lookup = full_schedule[['game_id', 'week']].drop_duplicates()

    # OFFENSE
    off_stats = (
        pbp_season.groupby(['game_id', 'posteam'])
        .agg(avg_epa=('epa', 'mean'),
             avg_yards=('yards_gained', 'mean'),
             play_count=('play_id', 'count'))
        .reset_index()
        .rename(columns={'posteam': 'team'})
    )

    off_stats = off_stats.merge(week_lookup, on='game_id', how='left')
    off_stats = off_stats[off_stats['week'] < target_week]
    off_stats = off_stats.sort_values(['team', 'week'])

    for feat in ['avg_epa', 'avg_yards', 'play_count']:
        off_stats[f'rolling_{feat}'] = (
            off_stats.groupby('team')[feat]
            .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
        )

    # DEFENSE
    def_stats = (
        pbp_season.groupby(['game_id', 'defteam'])
        .agg(allowed_avg_epa=('epa', 'mean'),
             allowed_avg_yards=('yards_gained', 'mean'),
             allowed_play_count=('play_id', 'count'))
        .reset_index()
        .rename(columns={'defteam': 'team'})
    )

    def_stats = def_stats.merge(week_lookup, on='game_id', how='left')
    def_stats = def_stats[def_stats['week'] < target_week]
    def_stats = def_stats.sort_values(['team', 'week'])

    for feat in ['allowed_avg_epa', 'allowed_avg_yards', 'allowed_play_count']:
        def_stats[f'rolling_{feat}'] = (
            def_stats.groupby('team')[feat]
            .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
        )

    # latest
    latest_off = off_stats.groupby('team').last().reset_index()
    latest_def = def_stats.groupby('team').last().reset_index()

    # merge
    for side, df in [('home_team', latest_off), ('away_team', latest_off)]:
        prefix = 'home_' if side == 'home_team' else 'away_'
        cols = [c for c in df.columns if c.startswith('rolling_')]
        rename_map = {c: f"{prefix}{c}" for c in cols}
        upcoming = upcoming.merge(
            df[['team'] + cols].rename(columns={'team': side, **rename_map}),
            on=side, how='left'
        )

    for side, df in [('home_team', latest_def), ('away_team', latest_def)]:
        prefix = 'home_' if side == 'home_team' else 'away_'
        cols = [c for c in df.columns if c.startswith('rolling_')]
        rename_map = {c: f"{prefix}{c}" for c in cols}
        upcoming = upcoming.merge(
            df[['team'] + cols].rename(columns={'team': side, **rename_map}),
            on=side, how='left'
        )

    # ── Diff features ─────────────────────────────────────────────────────────
    upcoming['epa_home_off_away_def_rolling_diff'] = upcoming['home_rolling_avg_epa'] - upcoming['away_rolling_allowed_avg_epa']
    upcoming['epa_home_def_away_off_rolling_diff'] = upcoming['home_rolling_allowed_avg_epa'] - upcoming['away_rolling_avg_epa']

    # ── (rest of your function stays EXACTLY the same) ──
    # 👉 No other changes needed for the bug you hit

    # ── Final feature check ───────────────────────────────────────────────────
    missing = [f for f in model_features if f not in upcoming.columns]
    if missing:
        print(f"  ⚠️  Week {target_week} missing {len(missing)} features: {missing}")
        for m in missing:
            upcoming[m] = 0

    upcoming = upcoming.fillna(upcoming.median(numeric_only=True))

    return upcoming

# ── Main backfill loop ────────────────────────────────────────────────────────

all_logs = []

for week_num in BACKFILL_WEEKS:
    print(f"\n{'='*50}")
    print(f"Processing week {week_num}...")

    upcoming = build_features_for_week(
        week_num, TARGET_SEASON, full_schedule, pbp_rp, allpro_df
    )

    if upcoming is None or upcoming.empty:
        print(f"  No games found for week {week_num} — skipping")
        continue

    # Run model
    X    = upcoming[model_features].copy()
    preds = pipeline.predict(X)

    # Build results
    results = upcoming[['game_id','home_team','away_team',
                         'gameday','spread_line']].copy()
    results['predicted_margin'] = preds.round(1)
    results['model_edge']       = (results['predicted_margin'] - results['spread_line']).round(1)
    results['recommendation']   = results.apply(
        lambda r: f"BET HOME ({r['home_team']})" if r['model_edge'] > 0
                  else f"BET AWAY ({r['away_team']})" if r['model_edge'] < 0
                  else "PASS", axis=1
    )

    # Get actual results
    actuals = full_schedule[
        (full_schedule['season'] == TARGET_SEASON) &
        (full_schedule['week']   == week_num)
    ][['game_id','result']].rename(columns={'result':'actual_margin'})

    results = results.merge(actuals, on='game_id', how='left')

    # Score
    results['home_covered']  = (results['actual_margin'] > results['spread_line']).astype('Int64')
    results['model_correct'] = (
        ((results['model_edge'] > 0) == (results['actual_margin'] > results['spread_line']))
        .astype('Int64')
    )

    # Add tracker columns
    results['season']    = TARGET_SEASON
    results['week']      = week_num
    results['mode']      = 'backfill'
    results['logged_at'] = datetime.now().strftime('%Y-%m-%d %H:%M')

    all_logs.append(results)

    correct = results['model_correct'].sum()
    total   = len(results)
    print(f"  ✅ Week {week_num} done — ATS: {correct}/{total} ({correct/total*100:.1f}%)")

# ── Save everything ───────────────────────────────────────────────────────────
tracker = pd.concat(all_logs, ignore_index=True)
tracker = tracker[[
    'game_id','home_team','away_team','gameday','spread_line',
    'predicted_margin','model_edge','recommendation',
    'season','week','logged_at','actual_margin',
    'home_covered','model_correct','mode'
]]

tracker.to_csv(TRACKER_PATH, index=False)
print(f"\n{'='*50}")
print(f"✅ Backfill complete — {len(tracker)} total games saved")
print(f"   Weeks: {tracker['week'].unique().tolist()}")

correct = tracker['model_correct'].sum()
total   = len(tracker)
print(f"   Overall ATS: {correct}/{total} ({correct/total*100:.1f}%)")

